import Link from 'next/link'
import { Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { ThemeToggle } from '@/components/ui/theme-toggle'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
export const metadata = { title:'Pricing', description:'Choose the perfect plan' }
const plans = [ { name:'Starter', description:'Perfect for individuals', price:'$9.99', interval:'month', features:['Up to 3 projects','Basic analytics','Email support','1GB storage'] }, { name:'Professional', description:'For growing teams', price:'$29.99', interval:'month', features:['Unlimited projects','Advanced analytics','Priority support','50GB storage','Team collaboration'] }, { name:'Enterprise', description:'For large orgs', price:'Custom', interval:null, features:['Everything in Pro','Dedicated support','Custom integrations','Unlimited storage','SLA'] } ]
export default async function PricingPage(){ return (
<SidebarProvider defaultOpen={false}>
<AppSidebar />
<div className='flex flex-col min-h-screen'>
<header className='sticky top-0 z-50 glass border-b border-border/50'><div className='container mx-auto px-4 lg:px-6 h-16 flex items-center justify-between'><div className='flex items-center gap-2'><SidebarTrigger className='-ml-1' /><Link className='flex items-center space-x-2' href='/'><div className='w-8 h-8 gradient-primary rounded-lg'/><span className='font-bold text-xl gradient-text'>SaaS Starter</span></Link></div><nav className='hidden md:flex items-center space-x-6 text-sm font-medium'><Link className='text-muted-foreground hover:text-foreground' href='/blog'>Blog</Link><Link className='text-muted-foreground hover:text-foreground' href='/sign-in'>Sign In</Link><ThemeToggle /></nav><div className='md:hidden'><ThemeToggle /></div></div></header>
<main className='flex-1'><section className='w-full py-12 md:py-24 lg:py-32'><div className='container mx-auto px-4 md:px-6'><div className='text-center mb-12'><h1 className='text-4xl font-bold tracking-tighter sm:text-5xl mb-4'>Simple, Transparent Pricing</h1><p className='text-xl text-muted-foreground max-w-[600px] mx-auto'>Start free and scale as you grow.</p></div><div className='grid gap-6 lg:grid-cols-3 lg:gap-8 max-w-5xl mx-auto'>{plans.map((plan)=> (<Card key={plan.name} variant={plan.name==='Professional'?'gradient':'glass'} className='relative flex flex-col justify-between h-full'><div><CardHeader className='text-center pb-4'><CardTitle className='text-2xl'>{plan.name}</CardTitle><CardDescription className='mt-2'>{plan.description}</CardDescription><div className='mt-6'><span className='text-4xl font-bold'>{plan.price}</span>{plan.interval && <span className='text-muted-foreground ml-2'>/{plan.interval}</span>}</div></CardHeader><CardContent className='pt-0'><ul className='space-y-3'>{plan.features.map((f)=> (<li key={f} className='flex items-center gap-3'><div className='w-5 h-5 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0'><Check className='w-3 h-3 text-primary'/></div><span className='text-sm'>{f}</span></li>))}</ul></CardContent></div><CardFooter className='pt-6'><Button className='w-full' variant={plan.name==='Professional'?'secondary':'default'} size='lg' asChild><Link href='/sign-up'>{plan.name==='Enterprise'?'Contact Sales':'Get Started'}</Link></Button></CardFooter></Card>))}</div></div></section></main>
</div>
</SidebarProvider>) }
